logging:
  level:
    org.springframework.cloud.gateway.filter.factory.CircuitBreakerGatewayFilterFactory: TRACE
    org.springframework.security: TRACE
    org.springframework.web: TRACE
    org.springframework.cloud.config.server.environment: DEBUG
    org.eclipse.jgit: DEBUG
    io.github.resilience4j: DEBUG
    org.springframework.cloud.gateway: TRACE

security:
  api-key: ${API_KEY}

services:
  user-service:
    url: ${USER_SERVICE_URL}/service/users

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

spring:
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      resourceserver:
        public-key-location: classpath:keys/public.pem
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path= /service/customers/**
          filters:
            - UserHeader
            - name: Retry
              args:
                retries: 3
                statuses:
                  - INTERNAL_SERVER_ERROR
                  - BAD_GATEWAY
            - name: CircuitBreaker
              args:
                name: customerService
                statusCodes:
                  - 500
                fallbackUri: forward:/service/customers/api/v1/fallback
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path= /service/users/**
          filters:
            - ApiKey
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path= /service/product/**
          filters:
            - UserHeader
        - id: search-service
          uri: lb://search-service
          predicates:
            - Path= /service/search/**
          filters:
            - UserHeader
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path= /service/inventory/**
          filters:
            - UserHeader

jwt:
  private-key: classpath:keys/private_key.pem
  public-key: classpath:keys/public_key.pem
  expiration-seconds: 3600
  issuer: shopsphere-gateway