security:
  api-key: ${API_KEY}

services:
  user-service:
    url: ${USER_SERVICE_URL}/service/users

jwt:
  private-key: classpath:keys/private_key.pem
  public-key: classpath:keys/public_key.pem
  expiration-seconds: 3600
  issuer: shopsphere-gateway

spring:
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      resourceserver:
        public-key-location: classpath:keys/public.pem
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path= /service/users/**
          filters:
            - ApiKey
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path= /service/customers/**
          filters:
            - UserHeader
            - name: Retry
              args:
                retries: 3
                statuses:
                  - INTERNAL_SERVER_ERROR
                  - BAD_GATEWAY
            - name: CircuitBreaker
              args:
                name: customerService
                statusCodes:
                  - 500
                fallbackUri: forward:/service/customers/api/v1/fallback
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path= /service/product/**
          filters:
            - UserHeader
        - id: search-service
          uri: lb://search-service
          predicates:
            - Path= /service/search/**
          filters:
            - UserHeader
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path= /service/inventory/**
          filters:
            - UserHeader
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path= /service/order/**
          filters:
            - UserHeader
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path= /service/payment/**
          filters:
            - UserHeader
        - id: shipping-service
          uri: lb://shipping-service
          predicates:
            - Path= /service/shipping/**
          filters:
            - UserHeader
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path= /service/notification/**
          filters:
            - UserHeader

