management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,gateway
  endpoint:
    health:
      show-details: always

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    root: INFO
    com.shopsphere: DEBUG
    org.springframework.kafka: INFO