spring:
  application:
    name: user-service
  main:
    allow-bean-definition-overriding: true
  r2dbc:
    url: r2dbc:postgresql://shopspherpostgresql.ch00as842a9d.ap-south-2.rds.amazonaws.com:5432/shopsphere?sslMode=REQUIRE
    username: shopsphere_admin
    password: shopsphere_admin
  jpa:
    hibernate:
      ddl-auto: update


security:
  api-key: admin123


app:
  security:
    enabled: false

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.springframework.security: TRACE

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}