spring:
  main:
    allow-bean-definition-overriding: true
  r2dbc:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update





security:
  api-key: ${API_KEY}


app:
  security:
    enabled: ${SECURITY}

