spring:
  main:
    allow-bean-definition-overriding: true
  r2dbc:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update





security:
  api-key: ${API_KEY}


app:
  security:
    enabled: ${SECURITY}

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.springframework.security: TRACE

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}