spring:
  r2dbc:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

security:
  api-key: ${API_KEY}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

